// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8bOn-erbGYJJd5l2JSpuhRYFjnZduhA',
    appId: '1:959866043470:web:fc0f970fedcba10692571f',
    messagingSenderId: '959866043470',
    projectId: 'inspireme-d2d23',
    authDomain: 'inspireme-d2d23.firebaseapp.com',
    storageBucket: 'inspireme-d2d23.firebasestorage.app',
    measurementId: 'G-QLBMS3V04F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz_moLhFWyg8mrz5wOtdsqc-r70YWSRhU',
    appId: '1:959866043470:android:afbb96d0dbf7ea4e92571f',
    messagingSenderId: '959866043470',
    projectId: 'inspireme-d2d23',
    storageBucket: 'inspireme-d2d23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_KA8SiEBNfMhHfLpfO1gOzg41f1_DjoY',
    appId: '1:959866043470:ios:6bb4210c5d155add92571f',
    messagingSenderId: '959866043470',
    projectId: 'inspireme-d2d23',
    storageBucket: 'inspireme-d2d23.firebasestorage.app',
    iosBundleId: 'com.example.inspireMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_KA8SiEBNfMhHfLpfO1gOzg41f1_DjoY',
    appId: '1:959866043470:ios:6bb4210c5d155add92571f',
    messagingSenderId: '959866043470',
    projectId: 'inspireme-d2d23',
    storageBucket: 'inspireme-d2d23.firebasestorage.app',
    iosBundleId: 'com.example.inspireMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF8bOn-erbGYJJd5l2JSpuhRYFjnZduhA',
    appId: '1:959866043470:web:aba86d2f072b2f8292571f',
    messagingSenderId: '959866043470',
    projectId: 'inspireme-d2d23',
    authDomain: 'inspireme-d2d23.firebaseapp.com',
    storageBucket: 'inspireme-d2d23.firebasestorage.app',
    measurementId: 'G-RE52KW83PD',
  );
}
